use_frameworks!

platform :ios, '13.0'

target 'Artificien_Example' do
  pod 'OpenMinedSwiftSyft', '~> 0.1.3-beta2'
  pod 'Artificien', :path => '../'

  target 'Artificien_Tests' do
    inherit! :search_paths

    
  end
end
